import { SignIn } from "@clerk/nextjs";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Fragment } from "react";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function Page() {
  return (
    <Fragment>
      <Dialog defaultOpen={true}>
        <DialogContent className="sm:max-w-[425px] ">
          <DialogHeader>
            <DialogTitle>Dear visitor</DialogTitle>
            <DialogDescription>Sign up with the mock account</DialogDescription>
          </DialogHeader>
          <div className="py-4">
            If you want to use the mock account to have a full anonymous
            experience of the app, please click on&nbsp;
            <span className="font-semibold ">Sign up</span> and sign up with the
            autogenerated info.
          </div>
          <DialogFooter>
            <Link className="w-full" href={"/sign-up"}>
              <Button className="w-full bg-green-400 text-black hover:bg-green-500">
                Sign up
              </Button>
            </Link>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <SignIn />
    </Fragment>
  );
}
